## Intro to numpy


### Defining and using vectors

In [1]:
import numpy as np

In [2]:
a = np.asarray([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
print(a.shape)

(4,)


In [5]:
a = a * 2

In [6]:
print(a)

[2 4 6 8]


In [8]:
b = [1,2,3,4]
b = b * 2

In [9]:
print(b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [17]:
print(a*a)

[ 4 16 36 64]


In [18]:
print(np.dot(a,a))

120


### Using matrices

In [10]:
A = np.asarray([[1,2,3,4], [2,3,4,5], [4,5,6,7]])

In [11]:
print(A.shape)
print(A)

(3, 4)
[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]


In [12]:
print(A[0, 0], A[1, 2])

1 4


In [14]:
print(A*2)

[[ 2  4  6  8]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [15]:
print(A**2)

[[ 1  4  9 16]
 [ 4  9 16 25]
 [16 25 36 49]]


In [16]:
print(A*A)

[[ 1  4  9 16]
 [ 4  9 16 25]
 [16 25 36 49]]


In [21]:
print(A*a)

[[ 2  8 18 32]
 [ 4 12 24 40]
 [ 8 20 36 56]]


In [22]:
print(A.shape, a.shape)

(3, 4) (4,)


In [23]:
print(A)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]


In [24]:
print(a)

[2 4 6 8]


In [25]:
print(np.dot(A,a))

[ 60  80 120]


### Much more capabilities

In [34]:
A = np.random.randn(5,5)

In [35]:
print(A)

[[ 1.23491972  0.7722991   0.98115022  0.2657546  -1.34296302]
 [-0.7924766   0.9298536  -0.15929517  2.02428352 -0.56995833]
 [-1.21372884 -0.11465923  0.64268664  0.43999768 -0.87721473]
 [-1.36566596  1.19233152 -0.08550775  0.79015939  1.27192116]
 [-0.75960737  0.17139415  1.70746711  0.09559757  1.78014003]]


In [37]:
A_inv = np.linalg.inv(A)

In [38]:
print(A_inv)

[[ 0.12979431  0.22616114 -0.55050287 -0.33308318  0.13704411]
 [ 0.53221287 -0.39583288  0.03866383  0.85161083 -0.31465581]
 [ 0.225935   -0.02712775  0.19473404 -0.15993433  0.37199775]
 [-0.23221957  0.79543335 -0.33269875 -0.54582835  0.30553998]
 [-0.20009797  0.1179207  -0.40754635 -0.04140747  0.27730801]]


In [39]:
I = np.dot(A, A_inv)
print(I)

[[ 1.00000000e+00  8.02554905e-17  4.76525709e-17 -1.39721314e-16
   7.10196097e-17]
 [-3.28942504e-18  1.00000000e+00 -4.41604655e-17  7.58388660e-17
   6.92776842e-18]
 [-2.29963292e-17 -8.82053430e-17  1.00000000e+00  2.17333524e-16
  -2.03395931e-16]
 [ 6.35693247e-17 -3.19420578e-17 -1.36701720e-18  1.00000000e+00
  -1.73788506e-17]
 [ 4.47304723e-17 -1.70655370e-19 -6.22873331e-17  1.42284556e-16
   1.00000000e+00]]


### Powerful indexing

In [40]:
I < 1e-5

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [41]:
I[I<1e-5]=0

In [42]:
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
I[1, 2]

0.0

In [45]:
I[1, 1]

0.9999999999999999

In [46]:
I[1:3, :]

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [47]:
I[:, 1:3]

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [48]:
I[1:3, 1:3]

array([[1., 0.],
       [0., 1.]])

In [51]:
I[2:0:-1, 1:3]

array([[0., 1.],
       [1., 0.]])

In [52]:
I[I>0.4]

array([1., 1., 1., 1., 1.])

### Helper functions

In [54]:
a = np.ones((5, 1))
print(a)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [56]:
a = np.ones((5, ))
print(a)

[1. 1. 1. 1. 1.]


In [58]:
a = np.zeros((5, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [63]:
b = np.zeros_like(I)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Solving a simple linear system

In [64]:
A = [[5, 2], [4, 1]]
b = [1, -1]

In [65]:
x = np.dot(np.linalg.inv(A), b)

In [66]:
print(x)

[-1.  3.]


In [67]:
print(np.dot(A,x))

[ 1. -1.]


In [68]:
x_other = np.linalg.solve(A,b)

In [69]:
print(x_other)

[-1.  3.]
